[package]
name = "crest-player"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"

reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
yt-dlp = "1.3.4"
rodio = "0.17"
dirs = "5.0"


